### ISSUE TITLE
Hide --debug option from nugetize tool

### ISSUE THREAD

**Issue by kzu** [devlooped/nugetizer#108]
This seems to have confused at least one user. It should not be used by regular users. It's for nugetizer development itself.

See https://github.com/devlooped/nugetizer/discussions/106

**Comment by jzabroski** [comment]
That makes sense as to why it was trying to launch Visual Studio to enable debugging.  How would I do that myself, given there appears to be no other way to debug nugetizer right now (e.g., trace logging to understand flow of execution, since MSBuild doesnt provide stack traces for errors to my knowledge)?

**Comment by kzu** [comment]
Just like you don't debug SDK Pack when things don't pack the way you want (not that unusual, he ;)), you shouldn't need to debug nugetizer either.

Please provide a concrete repro that errors/fails and it should be fixed in nugetizer itself. 

Thanks!
