### ISSUE TITLE
Packing with Microsoft.Build.NoTargets doesn't put dependency under proper target framework group when reference other Microsoft.Build.NoTargets project

### ISSUE THREAD

**Issue by denjmpr** [devlooped/nugetizer#155]
## Describe the Bug

Hi @kzu!
I want to create "Microsoft.Build.NoTargets" project which uses Library project as reference and another "Microsoft.Build.NoTargets" which uses another Library project and the first "Microsoft.Build.NoTargets" project as references.
In the generated package's nuspec file the first "Microsoft.Build.NoTargets" project should be in the proper target framework group dependency, but it is inside common group and target framework group dependency is empty:

```xml
<dependencies>
  <group>
    <dependency id="Common" version="1.0.0" />
  </group>
  <group targetFramework="net5.0" />
</dependencies>
```

## Steps to Reproduce

1. Open HierarchyTest.sln from attached file.
[HierarchyTest.zip](https://github.com/devlooped/nugetizer/files/7459598/HierarchyTest.zip)
2. Build HierarchyTest.sln solution with Visual Studio.
3. Unzip the result Core.1.0.0.nupkg file.
4. Open Core.nuspec file with some editor.
5. Observe - the "Common" package is inside common group dependency and there is empty net5.0 target framework group.

## Expected Behavior

The "Common" package is inside net5.0 target framework group dependency.

## Version Info

NuGetizer 0.7.5

**Comment by denjmpr** [comment]
@kzu,
I made a little donation, because fixing of this will help me mostly finish transition of my product packing to NuGetizer.
Thanks. 😉

**Comment by denjmpr** [comment]
Hi @kzu,
I found a way to workaround this behavior by setting TargetFramework="net5.0" attribute to Common.NuGet.msbuildproj project reference inside of Core.NuGet.msbuildproj project like so:
```xml
<ItemGroup>
  <ProjectReference Include="..\Common.NuGet\Common.NuGet.msbuildproj" TargetFramework="net5.0" />
  <ProjectReference Include="..\Core\Core.csproj" />
</ItemGroup>
```
I'm not sure if the original issue is designed behavior or actual bug, but the workaround resolves the problem.
Thanks.

**Comment by kzu** [comment]
Heya! Thanks for the donation!

Taking a look now. Sorry for the delay

**Comment by kzu** [comment]
Ok, [found the reason](https://github.com/devlooped/nugetizer/blob/main/src/NuGetizer.Tasks/NuGetizer.targets#L129), and it turns out it's "by design": the reasoning is that packaging projects can (and typically will) contain assets for multiple target frameworks. It's one of the main reasons why you'd want to have a packaging project in the first place, rather than just referencing the library (in your case), which *would* be framework specific.

There is another place where this is specified explicitly, as the [BuildOutputFrameworkSpecific](https://github.com/devlooped/nugetizer/blob/main/src/NuGetizer.Tasks/NuGetizer.Authoring.props#L27) property, for authoring projects (aka packaging projects).

It would require performing packaging project contents analysis to determine if it indeed provides more than one target framework specific assets in order to automagically set the behavior you are looking for. Note, that if the packaging project provides `build` (with no TFM) assets, we'd also need to account for that, as well as potentially `tools` and other arbitrary assets you might want to include. It can get quite complicated quite fast.

I'm tempted to change the condition that sets the packaging project as non-TFM specific by checking for both authoring project and `BuildOutputFrameworkSpecific!=true`, which would allow you to get the behavior you want with:

```xml
<PropertyGroup>
   <BuildOutputFrameworkSpecific>true</BuildOutputFrameworkSpecific>
</PropertyGroup>
```

This would override the property we set by default, and should then kick in the updated behavior. As you noted, though, passing a target framework explicitly also sets the returned items with that value, which is another alternative (although perhaps not as intuitive).
