### ISSUE TITLE
Inconsistent behaviour when using PrivateAssets="All" between different frameworks when packing as tool

### ISSUE THREAD

**Issue by quasarea** [devlooped/nugetizer#261]
## Describe the Bug

When I set 
```
    <PackageReference Update="@(PackageReference)" PrivateAssets="All" />
```
or individual PrivateAssets="All" on particular PackageReference, it works as designed for .net 6, but doesn't for .net framework and only partially for standard

## Steps to Reproduce

nugetize outcome

```
C:\git\SimpleFrameworkProject>nugetize .\PackagingFramework.sln 
Package: PackagingFramework.1.0.0.nupkg
         C:\git\SimpleFrameworkProject\PackagingFramework\bin\PackagingFramework.nuspec
    Authors              : Me
    Description          : Package Description
    DevelopmentDependency:
    Version              : 1.0.0
  Contents:
    /tools/
      DependencyFramework.dll
      DependencyFramework.pdb
      PackagingFramework.dll
      PackagingFramework.pdb



C:\git\SimpleFrameworkProject>nugetize .\PackagingStandard.sln
Package: PackagingStandard.1.0.0.nupkg
         C:\git\SimpleFrameworkProject\PackagingStandard\bin\PackagingStandard.nuspec
    Authors              : PackagingStandard
    Description          : Package Description
    DevelopmentDependency:
    Version              : 1.0.0
  Contents:
    /tools/
      DependencyStandard.dll
      DependencyStandard.pdb
      Newtonsoft.Json.dll <-   direct package reference included
      PackagingStandard.dll
      PackagingStandard.pdb



C:\git\SimpleFrameworkProject>nugetize .\PackagingNet.sln
Package: PackagingNet.1.0.0.nupkg
         C:\git\SimpleFrameworkProject\PackagingNet\bin\PackagingNet.nuspec
    Authors              : PackagingNet
    Description          : Package Description
    DevelopmentDependency:
    Version              : 1.0.0
  Contents:
    /tools/
      DependencyNet.dll
      DependencyNet.pdb
      DependencyNet.runtimeconfig.json
      EntityFramework.dll <-  referenced project package reference included
      EntityFramework.SqlServer.dll
      Newtonsoft.Json.dll
      PackagingNet.dll
      PackagingNet.pdb
      System.CodeDom.dll
      System.Configuration.ConfigurationManager.dll
      System.Data.SqlClient.dll
      System.Security.Permissions.dll
      System.Windows.Extensions.dll
```

## Expected Behavior

To be consistent

## Version Info

0.9.1

## Additional Info

Its a bit of a pain that all projects have to have PrivateAssets="All" in order to package correctly, I would expect that setting this only on packaging projects would do.

Attached sample projects that replicate the issue, run go.bat to restore/build/nugetize

[PackagingProject.zip](https://github.com/devlooped/nugetizer/files/10085170/PackagingProject.zip)

**Comment by kzu** [comment]
The `tools` folder is intended to be used for packing dotnet tools, which (by definition) need to be dotnet core (or net5+). In fact, as soon as you set `PackAsTool=true`, the .NET (6 and 7, at least) SDK targets, will validate that and you'll get the following error, which is expected:

```
Microsoft.NET.Sdk\targets\Microsoft.NET.PackTool.targets(95,5): error NETSDK10
54: only supports .NET Core. [...\PackagingProject\PackagingStandard\PackagingStandard.csproj]
``` 

The rules for what constitutes a "runtime dependency" for a given package given a target framework are non-trivial and depend largely on each package author, as well as nuget's own rules. For example, many packages provide mere metadata (aka "ref assemblies") in their netstandard lib folder, which basically will throw for any API you invoke on them, because the actual implementation are always for specific runtimes (i.e. .netcore/net5+ versus net472). Packing the "right" assembly provided by all package references for NS2 would be the "wrong thing" in this case.

Therefore, this is more or less intentional. It should work perfect for its intended target (netcore/net5+) and more or less unspecified behavior for anything else. 

You can very granularly control what's pulled in from each package reference by using the [advanced packing of package reference content](https://github.com/devlooped/nugetizer/#packing-arbitrary-files-from-referenced-packages), for example.

**Comment by quasarea** [comment]
Understood, thanks
