### ISSUE TITLE
SponsorLink warnings in VS builds that can't be suppressed and "build paused for Xms"?

### ISSUE THREAD

**Issue by Sergio0694** [devlooped/nugetizer#371]
## Overview

After updating NuGetizer recently, I've noticed a bunch of messages like these in VS builds:

![](https://user-images.githubusercontent.com/10199417/229289269-3913cbf5-e1cc-41b1-abfc-751ce4a2c572.png)

Contrary to messages like eg. DNG02, which can easily be suppressed, I couldn't find a way to suppress this one. Additionally, what's that "build paused for Xms" message? That doesn't sound encouraging. Regardless, I'm totally fine with people trying to incorporate more ways to push developers into doing sponsorship and it's of course their right, but that's not the approach I personally like and want to have in my build setup, nor one I would want others depending on my library to use. People can sponsor me if they like, and that's of course welcome, but I wouldn't want to inject anything like this into their build infrastructure. My issue is also with the fact that regardless of whether one is actually sponsoring or not, I wouldn't want them to have to then do more work to setup all the necessary stuff in their solution to _prove_ they did actually sponsor the project, so that the analyzer/targets can finally stop showing warnings.

Is there a way to completely suppress these warnings? I'm not asking to make any changes in this or related project, since as I said, of course anyone's free to do whatever they prefer. I'm just asking because if there is a way, I'd very happily just enable that. If not, I think I'll just remove the NuGetizer dependency entirely and just use a vanilla SDK-style .csproj to configure the packages I have.

Thank you! 🙂

**Comment by kzu** [comment]
Hi @Sergio0694 , thanks for your feedback! Please see https://www.cazzulino.com/sponsorlink.html for background on why I'm doing this.

> nor one I would want others depending on my library to use

Your library doesn't have a dependency on NuGetizer (or transitively, SponsorLink), since nugetizer is a *development* dependency. So nobody using your library will ever hear about SponsorLink.

The warning you're seeing is for *you*: as a developer taking advantage of NuGetizer, I'm asking *you* to sponsor *me* so I can continue working on it, improving it and fixing issues.

Does that clarify what you're seeing?
