### ISSUE TITLE
Floating version problem

### ISSUE THREAD

**Issue by dominikjeske** [devlooped/nugetizer#64]
I'm using nugetizer 0.6 and have following issue when using floating versions. In my project I have PackageReference like this

`<PackageReference Include="packageName" Version="1.0.1-preview.*" />`

on my artifactory I have this package in versions from preview.1 to preview.6 but package created from my project have dependency with version 1.0.1-**preview.0**

When nugetizer is removed from project package dependency have proper 1.0.1-preview.6 version which point to actual version. It looks like nugetizer is not handling floating versions properly?

**Comment by michalrosenbaum** [comment]
Just to visualize/help with reproducing, let's say that we have these packages in the feed:
`SomeDependencyOfNestedPack.1.0.0.nupkg`
`SomeDependencyOfNestedPack.1.0.1.nupkg`
	
If a nested project packed with the root package has the following reference with a floating version such as:
`<PackageReference Include="SomeDependencyOfNestedPack" Version="1.0.*" />`

The resulting version in the nuspec is going to be:
`<dependency id="SomeDependencyOfNestedPack" version="1.0.0" />`

The floating part always evaluates to "0". It creates a problem since it's not the latest version. 

This is how we reference Nugetizer:

```<ItemGroup>
<PackageReference Include="NuGetizer" Version="0.6.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>

**Comment by kzu** [comment]
You can't reference floating versions when packing. This is not supported in nuspec neither nuget packaging APIs, AFAIK. 

And it makes sense, since you would end up with non-deterministic packages where the exact same checkout/commit can produce different packages.

**Comment by maciejw** [comment]
@kzu this is interesting problem, but correct me if I'm wrong, restore can use floating version and pack is using version that was restored at the time, that is in package.assets.json? with lockfile (its an assets json that is commied to repo) you have deterministic restore and in nuspec you should have fixed version. 

even with fixed version in packagereferece you have kind of floating behavior, because version in package reference means version equal or greater and when packages is feed change, restore graph can change also, even if you are using same exact commit.

**Comment by kzu** [comment]
Fair point. This is very low priority for me personally since I never use checked-in lock files, so I get my determinism from the actual fixed versions in the package reference instead (and let dependabot bump those for me as needed).

I'll gladly take a PR that adds this behavior, though. Perhaps the right sponsorship level would also work :).

Thanks for clarifying the intended scenario and expected behavior :+1:
