### ISSUE TITLE
Generate package with symbols?

### ISSUE THREAD

**Issue by dominikjeske** [devlooped/nugetizer#80]
In my project we have following configuration for our nuget packages

```
  <PropertyGroup>
    <!-- Embed source files that are not tracked by the source control manager - compiler-generated source, like AssemblyInfo, are included in the PDB.-->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Source code embedded into pdb.-->
    <EmbedAllSources>true</EmbedAllSources>
    <!-- Defines the level of debug information that you want to be generated. Valid values are "full," "pdbonly," "portable", "embedded", and "none." -->
    <DebugType>portable</DebugType>
    <!-- A boolean value that indicates whether symbols are generated by the build. -->
    <DebugSymbols>true</DebugSymbols>
    <!-- This Boolean value indicates whether the package should create additional symbols package when the project is packed -->
    <IncludeSymbols>true</IncludeSymbols>
    <!-- If "snupkg", a snupkg symbol package is created containing the portable PDBs. -->
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
```

When configured project in that way we have two packages - one main package and package with format snupkg with symbols and source codes. Unfortunately when we add nugetizer to our project it generates only one package and symbols are integrated in same package. Can we generate snupkg when nugetizer is enabled?

**Comment by AraHaan** [comment]
I would combine the pdbs into the dlls and just ship the normal nuget package. It also helps reduce network load and speeds up debugging by not having to download the pdb in order to debug possible problems later.

That is why I changed my project from portable pdbs to embedded pdbs. This is because not everyone got fast internet. I know of people in countries that get less than 0.5 MB/s internet speeds.

**Comment by dominikjeske** [comment]
We have everything locally and we don't want to have pdbs+sources on prod (because we have both - sourelink with bitbucket is not so nice in corpo).

**Comment by kzu** [comment]
NuGetizer doesn't do separate symbol packages. That's mostly a legacy thing invented in a time where symbols weren't portable, were gigantic and other developer environments couldn't use them for anything useful aside from VS. That's now all changed with standard portable PPDBs, sourcelink and source (downloading+browsing) working almost everywhere.

So, this won't be added to NuGetizer.

**Comment by dominikjeske** [comment]
Thanks for the response. Can you write little more why this is legacy? My understanding is that this is standard behavior of SDK and most of the Microsoft packages are distributed that way with separate packages (correct me if I’m wrong). When I download packages I see that only binaries are inside (no pdb’s) and they are not embedded. So you are saying that proper solution is to server package with pdb’s to production?

As far as sourcelink is concerned it is great for github – for bitbucket I have some problems. Generally it works but there are some problems with authentication while debugging (sometimes auth window is displayed on second attempts, sometimes password is not remembered and things like this).

So I respect your statement that nugetizer will not support this but I just don’t feel that this is legacy.

**Comment by AraHaan** [comment]
This is why I usually embed the pdbs and ensure that all the source is embedded in the pdb which is embedded inside the assembly. Which can be fixed by simply telling sourcelink to always *include* all of the source files (even from fresh clones).

Infact I feel like the whole BCL *should* embed the pdb since they use sourcelink and github anyway and use portable pdbs nowdays. It's basically the same thing as portable pdbs but instead embedded and works on every OS as is.

**Comment by kzu** [comment]
+1 to PDB embedding also (perhaps except for mobile assemblies?). 

@dominikjeske this is just a personal opinion, of course: I think Microsoft invested heavily over the years in standardized (across teams) tooling to do the pdb + symbol server signing, publishing, updating, and it will just take time for portable PDBs and solidify sourcelink to the point it can replace the old stuff wholesale. 

Given packages are typically cached centrally on your machine, for all but a minority of scenarios (i.e. deploying to a mobile phone without much disk space or the like), there is no point in "saving" the significantly reduced space that PPDBs consume nowadays. I have been shipping every single one of my nuget packages with the symbols alongside the assemblies, like fovever. Nobody ever complained (think Moq-scale user base) about that approach. Sure, .NET SDK is gigantic in comparison, but I still think storage space-wise, it's pointless to have symbol packages. To me, it's all just legacy stuff that doesn't go away just because there's a decade+ invested on it and tooling and automation from lots of teams across lots of companies probably.
